"""Shared visual tokens for the PySide6 management console."""

FONT_FAMILY = (
    '"思源宋体 VF", "Source Han Serif SC", "Source Han Serif CN", '
    '"Microsoft YaHei UI", "Microsoft YaHei", serif'
)
FONT_SIZE_BODY = 14
FONT_SIZE_HINT = 12
FONT_SIZE_SECTION = 16
FONT_SIZE_PAGE = 20
FONT_SIZE_BRAND = 22

RADIUS_CHECKBOX = 3
RADIUS_PROGRESS = 5
RADIUS_CONTROL = 6
RADIUS_CARD = 8
RADIUS_WINDOW = 12

TEXT = "#1D1B16"
TEXT_HEADING = "#1A1A1A"
TEXT_SECONDARY = "#514D46"
TEXT_MUTED = "#625E56"
TEXT_DISABLED = "#A99C8F"
TEXT_ICON = "#777169"

CANVAS = "#F5F3EE"
SURFACE = "#FFFDF9"
SURFACE_STRONG = "#FFFFFF"
SURFACE_SUBTLE = "#F1EDE7"
SURFACE_HOVER = "#F7EDE2"
SURFACE_PRESSED = "#E3DDD4"
SURFACE_DISABLED = "#F0E8DF"
SURFACE_CONTROL = "#E9E4DC"
SURFACE_CONTROL_HOVER = "#DFD9D0"
SURFACE_CONTROL_PRESSED = "#D2CBC1"
SURFACE_SELECTED = "#F7E8E1"
SIDEBAR = "#EEEAE3"
SIDEBAR_HOVER = "#F0ECE6"
WINDOW_BUTTON_HOVER = "#E9E5DE"
WINDOW_BUTTON_PRESSED = "#DED8CF"
SCROLLBAR = "#C9C9C9"
SCROLLBAR_HOVER = "#B0B0B0"
PREVIEW = TEXT
PREVIEW_TEXT = "#D8D4CC"

BORDER = "#E5E0D8"
BORDER_SUBTLE = "#E1DCD4"
BORDER_CONTROL = "#D5CFC6"
BORDER_STRONG = "#C9C2B8"
BORDER_WINDOW = "#DAD5CD"
BORDER_SIDEBAR = "#DDD8CF"
BORDER_SELECTED = "#ECD5CB"
BORDER_CHECKBOX = "#8E887F"
BORDER_DISABLED = "#E8DED3"
BORDER_DANGER_DISABLED = "#D8C8C3"
BORDER_SIDEBAR_CONTROL = "#D8D2C9"

ACCENT = "#DA7756"
ACCENT_HOVER = "#E48766"
ACCENT_PRESSED = "#BF5F42"
ACCENT_DARK = "#6F2F20"
ACCENT_BORDER = "#C78F72"
ACCENT_BORDER_STRONG = "#9D4934"
ACCENT_DISABLED = "#EAB49F"
ACCENT_SUBTLE = "#F9E8E1"

SUCCESS = "#177A3D"
WARNING = "#8A4B20"
DANGER = "#B42318"
DANGER_HOVER = "#8F1D14"
DANGER_DARK = "#72170F"
DANGER_SURFACE_HOVER = "#FBE9E7"
DANGER_SURFACE_PRESSED = "#F4D2CE"
WINDOW_CLOSE_HOVER = "#C75B3A"
ON_ACCENT = "#FFF9F2"
ON_ACCENT_DISABLED = "#FFF9F6"

QSS_TOKENS = {
    "__FONT_FAMILY__": FONT_FAMILY,
    "__FONT_SIZE_BODY__": f"{FONT_SIZE_BODY}px",
    "__FONT_SIZE_HINT__": f"{FONT_SIZE_HINT}px",
    "__FONT_SIZE_SECTION__": f"{FONT_SIZE_SECTION}px",
    "__FONT_SIZE_PAGE__": f"{FONT_SIZE_PAGE}px",
    "__FONT_SIZE_BRAND__": f"{FONT_SIZE_BRAND}px",
    "__RADIUS_CHECKBOX__": f"{RADIUS_CHECKBOX}px",
    "__RADIUS_PROGRESS__": f"{RADIUS_PROGRESS}px",
    "__RADIUS_CONTROL__": f"{RADIUS_CONTROL}px",
    "__RADIUS_CARD__": f"{RADIUS_CARD}px",
    "__RADIUS_WINDOW__": f"{RADIUS_WINDOW}px",
    "__TEXT__": TEXT,
    "__TEXT_HEADING__": TEXT_HEADING,
    "__TEXT_SECONDARY__": TEXT_SECONDARY,
    "__TEXT_MUTED__": TEXT_MUTED,
    "__TEXT_DISABLED__": TEXT_DISABLED,
    "__TEXT_ICON__": TEXT_ICON,
    "__CANVAS__": CANVAS,
    "__SURFACE__": SURFACE,
    "__SURFACE_STRONG__": SURFACE_STRONG,
    "__SURFACE_SUBTLE__": SURFACE_SUBTLE,
    "__SURFACE_HOVER__": SURFACE_HOVER,
    "__SURFACE_PRESSED__": SURFACE_PRESSED,
    "__SURFACE_DISABLED__": SURFACE_DISABLED,
    "__SURFACE_CONTROL__": SURFACE_CONTROL,
    "__SURFACE_CONTROL_HOVER__": SURFACE_CONTROL_HOVER,
    "__SURFACE_CONTROL_PRESSED__": SURFACE_CONTROL_PRESSED,
    "__SURFACE_SELECTED__": SURFACE_SELECTED,
    "__SIDEBAR__": SIDEBAR,
    "__SIDEBAR_HOVER__": SIDEBAR_HOVER,
    "__WINDOW_BUTTON_HOVER__": WINDOW_BUTTON_HOVER,
    "__WINDOW_BUTTON_PRESSED__": WINDOW_BUTTON_PRESSED,
    "__SCROLLBAR__": SCROLLBAR,
    "__SCROLLBAR_HOVER__": SCROLLBAR_HOVER,
    "__BORDER__": BORDER,
    "__BORDER_SUBTLE__": BORDER_SUBTLE,
    "__BORDER_CONTROL__": BORDER_CONTROL,
    "__BORDER_STRONG__": BORDER_STRONG,
    "__BORDER_WINDOW__": BORDER_WINDOW,
    "__BORDER_SIDEBAR__": BORDER_SIDEBAR,
    "__BORDER_SELECTED__": BORDER_SELECTED,
    "__BORDER_CHECKBOX__": BORDER_CHECKBOX,
    "__BORDER_DISABLED__": BORDER_DISABLED,
    "__BORDER_DANGER_DISABLED__": BORDER_DANGER_DISABLED,
    "__BORDER_SIDEBAR_CONTROL__": BORDER_SIDEBAR_CONTROL,
    "__ACCENT__": ACCENT,
    "__ACCENT_HOVER__": ACCENT_HOVER,
    "__ACCENT_PRESSED__": ACCENT_PRESSED,
    "__ACCENT_DARK__": ACCENT_DARK,
    "__ACCENT_BORDER__": ACCENT_BORDER,
    "__ACCENT_BORDER_STRONG__": ACCENT_BORDER_STRONG,
    "__ACCENT_DISABLED__": ACCENT_DISABLED,
    "__ACCENT_SUBTLE__": ACCENT_SUBTLE,
    "__WARNING__": WARNING,
    "__DANGER__": DANGER,
    "__DANGER_HOVER__": DANGER_HOVER,
    "__DANGER_DARK__": DANGER_DARK,
    "__DANGER_SURFACE_HOVER__": DANGER_SURFACE_HOVER,
    "__DANGER_SURFACE_PRESSED__": DANGER_SURFACE_PRESSED,
    "__WINDOW_CLOSE_HOVER__": WINDOW_CLOSE_HOVER,
    "__ON_ACCENT__": ON_ACCENT,
    "__ON_ACCENT_DISABLED__": ON_ACCENT_DISABLED,
}
